### ISSUE TITLE
how many requests per month can this package handle?

### ISSUE THREAD

**Issue by rohan2734** [umaryusuf11/node-deep-email-validator#1]
how many requests per month can this package handle?

**Comment by umaryusuf11** [comment]
> how many requests per month can this package handle?

I believe that would depend on your server architecture.

**Comment by rohan2734** [comment]
i mean you are using the service called mailcheck and disposable email domains right, so isnt that dependent on it? they are completely free?

**Comment by FifineHex** [comment]
This is not an API where you pay per use, everything is hosted on your computer / server, both dependencies are open source and you can see for yourself how it works
